# Generated by Django 6.0 on 2025-12-20 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان العقد')),
                ('file', models.FileField(upload_to='contracts/', verbose_name='ملف العقد')),
                ('extracted_text', models.TextField(blank=True, null=True, verbose_name='النص المستخرج')),
                ('user_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات المستخدم')),
                ('analysis_report', models.TextField(blank=True, null=True, verbose_name='تقرير التحليل')),
                ('risk_score', models.IntegerField(default=0, verbose_name='مؤشر المخاطرة')),
                ('safe_version_text', models.TextField(blank=True, null=True, verbose_name='الصياغة الآمنة')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تم الدفع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المحامي/المستخدم')),
            ],
        ),
    ]
