# Generated by Django 6.0 on 2025-12-20 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'طلب خدمة', 'verbose_name_plural': 'إدارة طلبات العملاء'},
        ),
        migrations.AddField(
            model_name='contract',
            name='admin_private_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات خاصة لك (لا يراها العميل)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='service_type',
            field=models.CharField(choices=[('analyze', 'تحليل العقود وكشف الثغرات'), ('generate', 'توليد العقود الآمنة'), ('arbitration', 'التحكيم التجاري وشروط التحكيم'), ('pricing', 'طلب تسعير خاص')], default='analyze', max_length=20, verbose_name='نوع الخدمة'),
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('received', 'تم استلام الطلب'), ('reviewing', 'قيد المراجعة من قبلك'), ('completed', 'تم الانتهاء وإرسال النتائج'), ('rejected', 'مرفوض/نقص بيانات')], default='received', max_length=20, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='analysis_report',
            field=models.TextField(blank=True, null=True, verbose_name='تقريرك النهائي (المراجعة)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='extracted_text',
            field=models.TextField(blank=True, null=True, verbose_name='النص المستخرج آلياً'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='ملف العقد'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='تم دفع الرسوم'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='risk_score',
            field=models.IntegerField(default=0, verbose_name='مؤشر المخاطرة (تحدده أنت أو الذكاء الاصطناعي)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='safe_version_text',
            field=models.TextField(blank=True, null=True, verbose_name='الصياغة الآمنة المعتمدة'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان العقد/الطلب'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='user_notes',
            field=models.TextField(blank=True, null=True, verbose_name='بيانات الطلب (ملء العميل)'),
        ),
    ]
