# Generated by Django 6.0 on 2025-12-21 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contract_options_contract_admin_private_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'عقد', 'verbose_name_plural': 'العقود'},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='admin_private_notes',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='file',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='safe_version_text',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='user_notes',
        ),
        migrations.AddField(
            model_name='contract',
            name='order_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات العميل'),
        ),
        migrations.AddField(
            model_name='contract',
            name='original_file',
            field=models.FileField(default='temp.pdf', upload_to='contracts/originals/', verbose_name='الملف الأصلي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='analysis_report',
            field=models.JSONField(blank=True, null=True, verbose_name='تقرير التحليل'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='extracted_text',
            field=models.TextField(blank=True, null=True, verbose_name='النص المستخرج'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='تم الدفع'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='risk_score',
            field=models.IntegerField(default=0, verbose_name='درجة المخاطرة'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('processing', 'جاري المعالجة'), ('analyzing', 'جاري التحليل ذكياً'), ('completed', 'تم التحليل'), ('error', 'فشل في التحليل')], default='processing', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان العقد'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
