# Generated by Django 6.0 on 2025-12-22 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contract_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={},
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='order_notes',
            new_name='user_notes',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='extracted_text',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='original_file',
        ),
        migrations.AddField(
            model_name='contract',
            name='file',
            field=models.FileField(default=0, upload_to='contracts/originals/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='service_type',
            field=models.CharField(choices=[('analyze', 'تحليل العقود (AI)'), ('generate', 'صياغة العقود'), ('arbitration', 'التحكيم التجاري'), ('data_analytics', 'تحليل البيانات')], default=dict, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='analysis_report',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='تقرير التحليل المفصل'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='risk_score',
            field=models.IntegerField(default=0, verbose_name='مؤشر المخاطرة'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('paid', 'تم الدفع / جاري المعالجة'), ('completed', 'تم الانتهاء')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
